version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only: main

    steps:
      - add_ssh_keys:
          fingerprints:
            - "${READ_KEY}"
            - "${WRITE_KEY}"
      - checkout
      - run:
          name: install pnpm
          command: npm install pnpm -g
      - run:
          name: install dependence
          command: pnpm install -r
